README.md
Happy to contribute code. You can reach out to me on Teams too.
=> Stubbed out the README

Cargo.toml, README.md, proto/dapr.proto, src/client.rs
* Update 0.4.0 dapr proto files
* Update client
* Upgrade crate pkgs.
#6
=> Update 0.4.0 dapr proto to have multi stores

proto/dapr.proto
=> Update gRPC proto files to Dapr 0.5.0 version

dapr/proto/runtime/v1/dapr.proto, src/client.rs
Updated `runtime/v1/dapr.proto` from [dapr/dapr](https://github.com/dapr/dapr/blob/master/dapr/proto/runtime/v1/dapr.proto) and the corresponding client code for it. 
This PR will close: #15
=> Update runtime proto file

README.md
This simple thing will make the code snippet in the README.md file much more cool 😄
=> Beautify code snippet

examples/client/README.md, examples/pubsub/README.md
=> Replace deprecated cli options

dapr/proto/common/v1/common.proto, dapr/proto/runtime/v1/appcallback.proto, dapr/proto/runtime/v1/dapr.proto, examples/pubsub/publisher.rs, examples/pubsub/subscriber.rs, src/appcallback.rs, src/client.rs
=> Update proto clients and support multi pubsub

dapr/proto/runtime/v1/dapr.proto, examples/client/client.rs, src/appcallback.rs, src/client.rs
Added `metadata` argument support  for get/delete state APIs. 
Fixes #25  
Please make sure you've completed the relevant tasks for this PR, out of the following list:
=> Added metadata argument support for get/delete APIs 

dapr/proto/runtime/v1/appcallback.proto, dapr/proto/runtime/v1/dapr.proto
Update proto files for 0.11.0 dapr
Closes #27
=> Update proto files for 0.11.0 dapr

dapr/proto/runtime/v1/dapr.proto
Closes: #30 
Examples are validated with Dapr 1.0.0 RC.1
=> proto update

dapr/proto/runtime/v1/appcallback.proto, dapr/proto/runtime/v1/dapr.proto, examples/pubsub/publisher.rs, examples/pubsub/subscriber.rs, src/client.rs
* Update proto
* Update example following changes in proto
* Validated changed example with Dapr 1.0.0-RC.2
=> Update to 1.0.0-RC.2 proto

dapr/proto/common/v1/common.proto, dapr/proto/runtime/v1/dapr.proto, src/client.rs
* Update to 1.0.0-rc.3 protos
* Verified with local `cargo build` and `cargo build --examples`
=> Update to 1.0.0-rc.3 protos

Cargo.toml
=> Bump Rust SDK version

dapr/proto/runtime/v1/dapr.proto
=> feat: add shutdown

Cargo.toml, update-protos.sh
* Created a script to update proto files for release and ran it
* Version bump to `0.5.0-alpha.0`
=> Update proto clients in rust-sdk

Cargo.toml, examples/pubsub/publisher.rs
Updates dependencies to the current latest and bumped version number for incompatibility.
=> chore - update dependencies

Cargo.toml, dapr/proto/common/v1/common.proto, dapr/proto/runtime/v1/dapr.proto
=> Update protos and bump to v0.7.2-alpha.0

Cargo.toml
=> Bump version to 0.7.2

Cargo.toml, dapr/proto/runtime/v1/appcallback.proto, dapr/proto/runtime/v1/dapr.proto
Signed-off-by: Deepanshu Agarwal <deepanshu.agarwal1984@gmail.com>
=> Update protos and bump to v0.9.0-alpha.0

Cargo.toml, dapr/proto/common/v1/common.proto, dapr/proto/runtime/v1/appcallback.proto, dapr/proto/runtime/v1/dapr.proto
Signed-off-by: Deepanshu Agarwal <deepanshu.agarwal1984@gmail.com>
=> Update protos and bump to v0.10.0

.github/workflows/ci.yml, Cargo.toml, README.md, build.rs, examples/invoke/grpc-proxying/README.md, examples/invoke/grpc-proxying/client.rs, examples/invoke/grpc-proxying/server.rs, examples/invoke/grpc/README.md, examples/invoke/grpc/client.rs, examples/invoke/grpc/server.rs, examples/invoke/proto/helloworld.proto, rustfmt.toml
- Update dependencies
- Add example for invoke via gRPC
- Add example for invoke via gPRC proxying with custom server / client
=> Invoke examples

.github/workflows/ci.yml
Signed-off-by: Roberto J Rojas <robertojrojas@gmail.com>
=> Workflow - Install protoc

macros/Cargo.toml
=> Cargo manifest desc+licence 14

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request_or_proposal.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md
Minor fixes to the github templates including spacings and spellings/grammar.
=> fix: minor changes to github templates

.github/workflows/fossa.yml
=> chore: update fossa to run on main

.github/holopin.yml
The yaml file to award SDK badges had been updated such that each contributor can be awarded with a SDK badge for their contribution to this repo.
This PR will close #164
=> update holopin badge

README.md
Adds alpha notice.
Update minimum supported rust version to 1.56
Add discord social links
This PR will close #41
=> docs: add alpha notice and update docs

README.md
Only display the status from the main branch as opposed to all workflows including PRs.
=> docs: fix action badge

.github/workflows/validate-examples.yml, .github/workflows/validate-examples/details.json, examples/actors/dapr.yaml, examples/actors/resources/redis.yaml, examples/client/README.md, examples/client/resources/redis.yaml
Implements an updated workflow for testing dapr and cli changes when a commit reference is passed.
This also includes adding component specs to examples.
=> ci: upgrade CI enabling commit-based testing of cli and dapr

.gitignore
Adds the .idea config folder to gitignore
=> chore: add idea config to ignore

.github/workflows/validate-examples.yml, dapr/proto/runtime/v1/dapr.proto
pins the validation workflow to rc.4 and uses cli.6
protos have been bumped to rc.4
=> chore: bump to rc.4

src/lib.rs
=> Initialise docs 

.github/workflows/validate-examples.yml
Bumps runtime to rc11 and cli to rc8
=> chore: rc11 bump

examples/jobs/jobs.rs
=> remove irrelevant comment

Cargo.toml, macros/Cargo.toml
=> chore: bump version to 0.15 for release

README.md
=> docs: update rust min version

.github/workflows/ci.yml, dapr-macros/src/lib.rs
Deny warnings and fix macro type conversions flagged
=> refactor: deny warnings

examples/src/jobs/dapr.yaml
=> fix: include scheduler host address

Cargo.toml, README.md
=> chore(release): v0.16.0-rc.0

Cargo.toml, README.md
=> chore(release): update version

README.md, dapr/Cargo.toml
=> docs: update proto notice

.github/workflows/ci.yml, .github/workflows/validate-examples.yml
=> ci: add scheduled runs to test and validation workflows

.github/workflows/validate-examples.yml
=> fix(ci): trim blank spaces from version strings

.github/workflows/validate-examples.yml
=> fix(ci): fix installer bundle creation logic

.github/workflows/validate-examples.yml
=> Fix workflow

dapr/src/client.rs, daprdocs/content/en/rust-sdk-docs/rust-client/_index.md, examples/src/client/client.rs
=> refactor state methods

daprdocs/README.md, daprdocs/content/en/rust-sdk-docs/rust-client/_index.md
WIP
This PR will close #240 and #241
=> Update Dapr Rust docs

Cargo.toml, README.md
=> chore: bump rc versions

.github/workflows/ci.yml, Makefile
Adds proto diff check and refactors the test github workflow
=> feat: add proto check and make directives

Cargo.toml, dapr/Cargo.toml, dapr/src/lib.rs, dapr/src/server/actor/tests.rs
=> chore: remove macro dep from main crate

.github/workflows/ci.yml
=> ci: add dry publish test

.github/workflows/validate-examples.yml
=> Bump runtime

Cargo.toml, README.md, dapr/src/client.rs, daprdocs/content/en/rust-sdk-docs/rust-client/_index.md, examples/src/conversation/main.rs
=> feat(client): add a client port override method

dapr/Cargo.toml
=> fix(deps): pin indirect dependencies

Cargo.toml, README.md
=> release: v0.16.0

.github/workflows/validate-examples.yml
=> chore: remove pinned release versions validation

.github/workflows/validate-examples.yml
=> chore: remove pinned release versions validation (#270)

dapr/src/server/actor/runtime/mod.rs
=> fix(docs): over indented docs

.github/workflows/validate-examples.yml, dapr/Cargo.toml, dapr/src/server/actor/runtime/mod.rs
=> rebase main onto release

Cargo.toml, README.md, daprdocs/content/en/rust-sdk-docs/rust-client/_index.md
=> chore(release): bump versions

.github/workflows/ci.yml
=> chore: limit the visibility of the cargo token

dapr-macros/src/lib.rs, dapr/src/client.rs, dapr/src/error.rs, dapr/src/server/actor/mod.rs, dapr/src/server/actor/runtime/mod.rs, dapr/src/server/actor/tests.rs, dapr/src/server/http.rs, dapr/src/server/utils.rs, examples/src/actors/client.rs, examples/src/actors/server.rs, examples/src/bindings/input.rs, examples/src/configuration/main.rs, examples/src/invoke/grpc-proxying/client.rs, examples/src/invoke/grpc-proxying/server.rs, examples/src/invoke/grpc/client.rs, examples/src/invoke/grpc/server.rs, examples/src/jobs/jobs.rs, examples/src/pubsub/publisher.rs, examples/src/pubsub/subscriber.rs, examples/src/query_state/query1.rs, examples/src/query_state/query2.rs, proto-gen/src/main.rs
=> fix: refactor log formatting

daprdocs/content/en/rust-sdk-contributing/rust-contributing.md, daprdocs/content/en/rust-sdk-docs/_index.md, daprdocs/content/en/rust-sdk-docs/rust-client/_index.md
Update markdown files to be compatible with the latest Hugo version.
https://github.com/dapr/docs/issues/4673
=> Update markdown files to be compatible with latest Hugo

examples/src/jobs/jobs.rs
=> fix: cleanup dead code
