Cargo.toml, README.md, build.rs, examples/client.rs, proto/dapr.proto, proto/daprclient.proto, src/client.rs, src/error.rs, src/lib.rs
The beginnings of the crate. This simply gets a DaprClient struct in place that can invoke methods on a service. 
This differs from @flier's implementation in that it tries to hide the underlying gRPC library from the public API. This means that the user cannot rely on the fact that we're currently using the `tonic` crate. It also does not make the generated bindings public so the user can only use the hand written API built on top of the generated bindings. 
The error types in this PR are just stubs and need to be expanded out.
=> Scaffold the Rust project

Cargo.toml, src/client.rs
This fills out remaining client functionality. 
I'm not sure `Client` is the right name. Do we have a good sense for what this struct should be called? Especially considering that there will be more code generated from the `daprclient.proto` file, and I'm not sure what to call the struct that wraps that code.
=> Add more client methods

.github/workflows/ci.yml, Cargo.toml, README.md
- Added CI pipeline to automate cargo crate publish on crates.io 
- Updated README with instructions on how to use published crate
This PR will close: #33
=> Automate cargo crate publish process 

Cargo.toml
Aligns with Dapr Runtime release 1.1.0.
=> Version bump to 0.5.0

README.md
The dependency and version for Cargo.toml is mentioned in the README so it needs to be kept up to date also.
=> Updating the version in README

Cargo.toml, README.md, dapr/proto/runtime/v1/dapr.proto, update-protos.sh
Signed-off-by: Deepanshu Agarwal <deepanshu.agarwal1984@gmail.com>
Updates protos and bumps to v0.8.0-alpha.0.
Changes to fetch protos from a particular version of runtime in update-protos.sh. If nothing provided, by default picks protos from master.
=> Update protos, bump to v0.8.0-alpha.0 and fetch protos from corresponding runtime

examples/pubsub/README.md
It appears as if some of the example docs were copied from the python example. This change simply updates the name of the DAPR app in the example
=> Small pub/sub example doc fix

Cargo.toml, dapr/proto/common/v1/common.proto, dapr/proto/runtime/v1/appcallback.proto, dapr/proto/runtime/v1/dapr.proto, src/error.rs
Signed-off-by: Roberto J Rojas <robertojrojas@gmail.com>
=> Updates gRPC proto - dapr v1.10 release

update-protos.sh
`/bin/bash` is not always present.
=> Set `update-protos.sh` hashbang to `#!/usr/bin/env bash`

README.md, dapr/proto/runtime/v1/dapr.proto
Updating protos for Dapr 1.12 (pulling from `master`, since the 1.12 release is not created yet)
=> Updating protos for Dapr 1.12

dapr/proto/runtime/v1/dapr.proto
Run ./update-protos.sh with RUNTIME_RELEASE_TAG="v1.12.4"
=> Update proto 1.12.4

Cargo.toml, examples/configuration/main.rs, src/client.rs
This PR would address https://github.com/dapr/rust-sdk/issues/117
Adds a `metadata` parameter to the client's existing `get_configuration` and `subscribe_configuration` implementations. The new `metadata` parameter matches existing function signatures (from `get_state`, for example).
Callers would need to include optional metadata:
```
let mut stream = client
.subscribe_configuration(CONFIGSTORE_NAME, vec![(&key)], None)
.await?;
```
=> Handle metadata for get_configuration and subscribe_configuration

.github/workflows/ci.yml, Cargo.toml, examples/actors/README.md, examples/actors/server.rs, macros/Cargo.toml, macros/src/lib.rs, src/server/actor/mod.rs, src/server/actor/tests.rs, src/server/http.rs, src/server/utils.rs
Including in this PR:
- Upgrade of axum from 0.6.19 to 0.7.4
- Upgrade of dependencies that depend on axum
- Upgrade of env_logger crate
- Export axum from dapr::server::actor
- Use absolute paths in actor proc macro to use axum from dapr and not from the client
- Upgrade of toolchain as it was failing at resolving dependency/feature of env_logger
=> Upgrade axum to 0.7.4

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/discussion.md, .github/ISSUE_TEMPLATE/feature_request_or_proposal.md, .github/ISSUE_TEMPLATE/question.md
This PR is non-code related and will add issue templates for the GitHub repo.
Not an RFQ but feedback would be appreciated (open to reviews) on whether you think having a separate template for feature requests/proposals would be a good idea. I think they're almost the same and the standard template across the Dapr ecosystem is a bit lighter if you use the proposal template.
Will close #104
=> add github issue templates

CONTRIBUTING.md, README.md
Two minor suggested updates to the docs:
* Starting in [v0.11](https://github.com/tokio-rs/prost/releases/tag/v0.11.0), `prost` no longer bundles `protoc` and will no longer attempt to download the compiler if one doesn't already exist. Users will need protoc installed to work with the SDK so worth noting that as a pre-req IMO
* The Contributing docs had a reference to using the `vendor` directory for 3rd party Go modules which seemed out of place to me and a potential copy/paste leftover from another repo 
Note that I opted to make these separate commits particularly in case I'm missing some context around that `vendor` directory and 6231e56bc83165c765b9dd02ca5a4b0998771a38 is not desired, but I can certainly squash the changes together if you'd prefer both in a single commit
=> Couple doc updates

.github/workflows/validate-examples.yml, Cargo.toml, examples/secrets-bulk/README.md, examples/secrets-bulk/app.rs, examples/secrets-bulk/resources/local-secret-store.yaml, examples/secrets-bulk/secrets.json, src/client.rs
Addresses #122 with implementation + example
=> Implement bulksecret retrieval

.github/workflows/ci.yml, .github/workflows/validate-examples.yml, Cargo.toml, examples/jobs/README.md, examples/jobs/dapr.yaml, examples/jobs/jobs.rs, src/client.rs, src/server/appcallbackalpha.rs, src/server/mod.rs
Implement the scheduling/jobs api
=> feat: implement scheduler/jobs api

README.md
=> docs: update versions

.github/workflows/validate-examples.yml
Explicitly authenticates protoc step which is currently hitting rate limits
Also adds a baseline scope to the tokens - packages already are a default read-only option for the token.
Contributes towards: #168
=> ci: explicitly authenticate protoc setup step

dapr/proto/runtime/v1/dapr.proto
=> docs: fix comments

Cargo.toml, build.rs, dapr/proto/runtime/v1/dapr.proto, macros/Cargo.toml
Minor fixes to enable docs to build
=> fix: add experimental proto optionals and cleanup protos for 1-rc.1

.github/workflows/ci.yml, .github/workflows/dapr-bot/Cargo.toml, Cargo.toml, README.md, dapr-macros/Cargo.toml, dapr-macros/src/lib.rs, dapr/Cargo.toml, dapr/src/dapr/dapr.proto.common.v1.rs, dapr/src/dapr/dapr.proto.runtime.v1.rs, examples/Cargo.toml, examples/src/invoke/protos/helloworld.rs, proto-gen/Cargo.toml
=> chore(deps): upgrade deps and regen protos

.github/workflows/ci.yml, Cargo.toml, README.md, dapr/Cargo.toml, dapr/README.md, dapr/src/lib.rs
=> fix: release fixes

Cargo.toml, README.md
=> chore: release versioning

daprdocs/content/en/rust-sdk-docs/rust-client/_index.md
=> docs: clarify and fix mistakes

dapr/src/server/http.rs
By default the fallback handler now logs the path that could not be
found.
This can be vital for debugging, as otherwise there is no feedback on
the server if a method is called that isn't registered.
None
I believe it shouldn't be necessary to update the documentation or add new tests (the test_actor_deactivate call already tests 404 behavior).
=> Add fallback handler to axum Router

daprdocs/README.md
=> docs: fix typo

daprdocs/content/en/rust-sdk-docs/_index.md
=> docs: fix pane
